### ISSUE TITLE
Use official URL for Better

### ISSUE THREAD

**Issue by zorae** [anarki999/Adblock-List-Archive#3]
You currently list a copy of the Better.fyi filterlist that you host yourself. To ensure subscribers get the latest version, please change the default to the official URL:
`https://better.fyi/blockerList.txt`

**Comment by anarki999** [comment]
Nah, that's a different tracker list.

https://better.fyi/trackers/alexa-top-500-news/

I use the list from here. And manually enter all the filter by myself.
I also add tons of anti-detecting filter so that most of the website are unable to detect our adblocker, make the defense more powerful than ever
